# Generated by Django 4.2.19 on 2025-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lg_pricing", "0003_auto_20190709_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="lgrsentityhistory",
            name="seller",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="lgrsentitysectionposition",
            name="is_sponsored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lgrsentitysectionposition",
            name="seller",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
