# Sample configuration file for a logstash instance receiving logging from django
# Change the elasticsearch params as needed

input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    ssl => true
    cacert => "http_ca.crt"
    index => "logs-store_update"
    user => "elastic"
    password => "password"
  }
  stdout { codec => rubydebug }
}
