# Generated by Django 4.2.19 on 2025-02-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0088_alter_solotodouser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="ai_association_errors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
