# Generated by Django 4.2.19 on 2025-02-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0089_entity_ai_association_errors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entity",
            old_name="ai_association_errors",
            new_name="ai_inferred_product_data",
        ),
    ]
