# Generated by Django 4.2.19 on 2025-03-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "solotodo",
            "0090_rename_ai_association_errors_entity_ai_inferred_product_data",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="ai_association_similar_products",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
