# Generated by Django 4.2.19 on 2025-03-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0091_entity_ai_association_similar_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ai_confidence_threshold",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
