# Generated by Django 4.2.19 on 2025-03-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0092_category_ai_confidence_threshold"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="ai_confidence_threshold",
            new_name="ai_confidence_threshold_for_association",
        ),
        migrations.AddField(
            model_name="category",
            name="ai_additional_prompt_instructions_for_similarity_search",
            field=models.CharField(blank=True, null=True),
        ),
    ]
