# Generated by Django 4.2.19 on 2025-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "solotodo",
            "0093_rename_ai_confidence_threshold_category_ai_confidence_threshold_for_association_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="ai_additional_prompt_instructions_for_similarity_search",
            field=models.TextField(blank=True, null=True),
        ),
    ]
