# Generated by Django 4.2.19 on 2025-03-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "solotodo",
            "0094_alter_category_ai_additional_prompt_instructions_for_similarity_search",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="ai_association_similar_products",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="ai_inferred_product_data",
        ),
        migrations.AddField(
            model_name="entity",
            name="ai_association_result",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
