# Generated by Django 4.2.19 on 2025-05-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0095_remove_entity_ai_association_similar_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="scraped_categories",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="solotodo.category"
            ),
        ),
    ]
