# Generated by Django 4.2.19 on 2025-05-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0096_entity_scraped_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeupdatelog",
            name="registry_file",
        ),
    ]
