# Generated by Django 4.2.19 on 2025-05-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0097_remove_storeupdatelog_registry_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSectionPositionsUpdateLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "In process"),
                            (3, "Success"),
                            (4, "Error"),
                        ],
                        default=1,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("concurrency", models.IntegerField()),
                ("use_async", models.BooleanField()),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="solotodo.store"
                    ),
                ),
            ],
            options={
                "ordering": ["store", "-creation_date"],
            },
        ),
    ]
