# Generated by Django 4.2.19 on 2025-05-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0098_storesectionpositionsupdatelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storesection",
            name="name",
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
