# Generated by Django 4.2.19 on 2025-05-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0099_alter_storesection_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="description",
            field=models.TextField(db_index=True, null=True),
        ),
    ]
