# Generated by Django 4.2.19 on 2025-06-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0099_alter_storesection_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("params", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solotodo.category",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "name"),
            },
        ),
    ]
