# Generated by Django 4.2.19 on 2025-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0100_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="meta_tag_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
