# Generated by Django 4.2.19 on 2025-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0101_subcategory_meta_tag_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="meta_tag_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
