# Generated by Django 4.2.19 on 2025-07-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0102_category_meta_tag_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitysectionposition",
            name="is_sponsored",
            field=models.BooleanField(default=False),
        ),
    ]
