# Generated by Django 4.2.19 on 2025-07-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0103_entitysectionposition_is_sponsored"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitysectionposition",
            name="is_sponsored",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
