# Generated by Django 4.2.19 on 2025-09-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0104_alter_entitysectionposition_is_sponsored"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="max_discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
