# Generated by Django 4.2.19 on 2025-09-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0105_coupon_max_discount_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entity",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("backend_list_entities", "Can view entity list in backend"),
                    (
                        "backend_view_entity_conflicts",
                        "Can view entity conflicts in backend",
                    ),
                    (
                        "backend_view_entity_estimated_sales",
                        "Can view the entity estimated sales interface in backend",
                    ),
                    (
                        "backend_view_pending_entities",
                        "Can view the pending entities interface in the backend",
                    ),
                ],
            },
        ),
    ]
