# Generated by Django 4.2.19 on 2025-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0106_alter_entity_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ai_additional_prompt_instructions_for_product_data_inferring",
            field=models.TextField(blank=True, null=True),
        ),
    ]
