# Generated by Django 4.2.19 on 2025-08-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0104_alter_entitysectionposition_is_sponsored"),
        ("wtb", "0018_alter_wtbentity_picture_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="wtbentity",
            name="scraped_categories",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="solotodo.category"
            ),
        ),
    ]
