# Generated by Django 4.2.19 on 2025-08-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wtb", "0019_wtbentity_scraped_categories"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wtbentity",
            unique_together={("brand", "key")},
        ),
    ]
