# Generated by Django 4.2.19 on 2025-08-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wtb", "0020_alter_wtbentity_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wtbentity",
            name="is_active",
        ),
    ]
