# Generated by Django 4.2.19 on 2025-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_auto_20200817_2104"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportdownload",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "In process"),
                    (3, "Success"),
                    (4, "Error"),
                ],
                default=1,
            ),
        ),
    ]
