# Generated by Django 4.2.19 on 2025-09-11 14:46

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_reportdownload_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportdownload",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(
                    custom_domain=None, default_acl="private"
                ),
                upload_to="",
            ),
        ),
    ]
